dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

# before_install:

# command to install dependencies
install:
  # - pip install pytest
  - pip install pipreqs
  - pipreqs --debug --ignore practicum-atp,.git,.pytest_cache,.vscode,__pycache__ .
  - pip install -r requirements.txt
  - chmod +x prepare.sh
  - bash ./prepare.sh

# before_script:

# command to run tests
script: pytest

# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy:
