dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

# before_install:

# command to install dependencies
install:
  - pip install pipreqs
  - pipreqs --debug --ignore practicum-atp,.git,.vscode,__pycache__ .
  - pip install -r requirements.txt
  - chmod +x prepare.sh
  - bash ./prepare.sh
  - sudo apt install arm-none-eabi-gcc binutils
  - sudo apt install make cmake

# before_script:

# command to run tests
script: python -m unittest

# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy:
